spring:
  application:
    name: CoCoNut-was

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    gcp:
      project-id: coconut-was
      storage:
        bucket-name: coconut_bucket
      credentials:
        location: file:${GOOGLE_APPLICATION_CREDENTIALS}


jwt:
  secret-key: ${SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}