name: CoCoNut-was CI/CD with GitHub Actions

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar_path: ${{ steps.get_jar_path.outputs.path }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x ./gradlew
      - name: Build without Test
        run: ./gradlew build -x test --no-daemon
        env:
          GRADLE_OPTS: -Xmx2048m
      - name: Get JAR file path
        id: get_jar_path
        run: |
          JAR_PATH=$(find build/libs -name "*.jar")
          echo "path=${JAR_PATH}" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ${{ steps.get_jar_path.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-jar
      - name: Get JAR file path
        id: get_jar_path
        run: |
          JAR_PATH=$(find . -name "*.jar")
          echo "path=${JAR_PATH}" >> $GITHUB_OUTPUT
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: ${{ steps.get_jar_path.outputs.path }}
          target: "/home/ubuntu/CoCoNut-was"
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/CoCoNut-was
            pgrep -f '.jar' | xargs -r kill -9
            JAR_NAME=$(ls -t *.jar | head -n 1)
            DB_URL="${{ secrets.DB_URL }}" \
            DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            nohup java -jar $JAR_NAME > /dev/null 2>&1 &